travis:
  secure:
    BINSTAR_TOKEN: b30kQIsxDSXf7j6jKOR/tCjiBDEF/ZqwKoLBS8g6BbzvMzW0QevRA9nx8p7FEfZ7fst3HZs55FDZsF7Yg1JnMsmkXZyfXfDHnnXqp3tjq/Sks07G5xXYGhQosKgnYwcDC/sDYDNO+5JvyW1p1vGLe2DP9sCzlaf8emjXKeE8ELSgBeU3y6lK8aFjoB0rj+OpgFn9Sm4PGV+nbF2NZ8t8dGPjFyi4DS6zHvzAd01TaXlGSX1lyVRNc4ueCZAympEF7EMqiVmaYGkAgYZo6IvmzcUsfqtiBtiJZCkWMJb+vgOha3BSyztPyT37Xj5ac+uUuA+xTKjuTMjcM5x3nUcokbCAaiTyDnnbRAlMm0+n5h+B5t5gbTDWSxPEPE/0XV+dPC8OCouXFUyXiyY/9QFIf3rdv/c6u1Xg1YNAYknTLpoIFT0WyWdegNXk0oCUyVpVj2Eh+Iml0stEfsXai3o1FTLpx4+s20nmTYSTTjemC6D5AZ2FzP844u0Wt7lwCZB1WPn8rkjaWAup67RZhXSLQ8pvFhpAiglNoinj5ZNhd6kQwXQG4UXxv7DOw7nHm0YAo2jfx17Flu7EOQZGi8jQF5pfsIpTZMv13J2h/Y4d464bK8Vj/EydUjfvv43hHgT+aFdesA66uzCrmahobTgKct623dSFu+0PUhUrDj2KBjg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
